cit: fuji: Remove SMB_XP3R3V_TCXO from sensor list
Summary:
# Description

The PR removes the SMB_XP3R3V_TCXO sensor from the CIT sensor list for the Fuji platform.

# Motivation

The SMB_XP3R3V_TCXO sensor probing has been removed from the BMC image as part of pull request PR: [1766](https://github.com/facebookexternal/openbmc.celestica/pull/1766), hence removing the respective sensor from the CIT list of sensors.

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1767

Test Plan:
Before fix: [mp2_cit_log.txt](https://github.com/facebookexternal/openbmc.celestica/files/15412740/mp2_cit_log.txt)
```
======================================================================
FAIL: test_smb_sensor_keys (tests.fuji.test_sensor.SmbSensorTest.test_smb_sensor_keys) (key='SMB_XP3R3V_TCXO')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/fuji/test_sensor.py", line 434, in test_smb_sensor_keys
    self.assertIn(
AssertionError: 'SMB_XP3R3V_TCXO' not found in dict_keys(['present', 'SMB_XP3R3V_BMC', 'SMB_XP2R5V_BMC', 'SMB_XP1R8V_BMC', 'SMB_XP1R2V_BMC', 'SMB_XP1R0V_FPGA', 'SMB_XP3R3V_USB', 'SMB_XP5R0V', 'SMB_XP3R3V_EARLY', 'SMB_LM57_VTEMP', 'SMB_XP1R8', 'SMB_XP1R2', 'SMB_VDDC_SW', 'SMB_XP3R3V', 'SMB_XP1R8V_AVDD', 'SMB_XP1R2V_TVDD', 'SMB_XP0R75V_1_PVDD', 'SMB_XP0R75V_2_PVDD', 'SMB_XP0R75V_3_PVDD', 'SMB_VDD_PCIE', 'SMB_XP0R84V_DCSU', 'SMB_XP0R84V_CSU', 'SMB_XP1R8V_CSU', 'SMB_OUTPUT_VOLTAGE_XP0R75V_1', 'SMB_OUTPUT_CURRENT_XP0R75V_1', 'SMB_INPUT_VOLTAGE_1', 'SMB_OUTPUT_VOLTAGE_XP1R2V', 'SMB_OUTPUT_CURRENT_XP1R2V', 'SMB_OUTPUT_VOLTAGE_XP0R75V_2', 'SMB_OUTPUT_CURRENT_XP0R75V_2', 'SMB_INPUT_VOLTAGE_2', 'SIM_LM75_U1_TEMP', 'SMB_LM75B_U51_1_TEMP', 'SMB_LM75B_U57_TEMP', 'SMB_LM75B_U39_TEMP', 'SMB_VDDC_SW_TEMP', 'SMB_XP12R0V_VDDC_SW_IN', 'SMB_VDDC_SW_IN_SENS', 'SMB_VDDC_SW_POWER_IN', 'SMB_VDDC_SW_POWER_OUT', 'SMB_VDDC_SW_CURR_IN', 'SMB_VDDC_SW_CURR_OUT', 'PDB_L_TMP75_U2_TEMP', 'PDB_L_TMP75_U3_TEMP', 'PDB_R_TMP75_U2_TEMP', 'PDB_R_TMP75_U3_TEMP', 'FCB_FCM1_TMP75_U1_TEMP', 'FCB_FCM1_TMP75_U2_TEMP', 'FCB_FCM2_TMP75_U1_TEMP', 'FCB_FCM2_TMP75_U2_TEMP', 'FCM-T_CHIP_INPUT_VOLTAGE', 'FCM-T_POWER_CURRENT', 'FCM-T_POWER_VOLTAGE', 'FCM-B_CHIP_INPUT_VOLTAGE', 'FCM-B_POWER_CURRENT', 'FCM-B_POWER_VOLTAGE', 'FAN1_FRONT_SPEED', 'FAN1_REAR_SPEED', 'FAN2_FRONT_SPEED', 'FAN2_REAR_SPEED', 'FAN3_FRONT_SPEED', 'FAN3_REAR_SPEED', 'FAN4_FRONT_SPEED', 'FAN4_REAR_SPEED', 'FAN5_FRONT_SPEED', 'FAN5_REAR_SPEED', 'FAN6_FRONT_SPEED', 'FAN6_REAR_SPEED', 'FAN7_FRONT_SPEED', 'FAN7_REAR_SPEED', 'FAN8_FRONT_SPEED', 'FAN8_REAR_SPEED', 'SMB_SENSOR_TH4_HIGH']) : Missing key SMB_XP3R3V_TCXO in SMB sensor data

----------------------------------------------------------------------
Ran 405 tests in 1377.992s

FAILED (failures=2, skipped=2)
```
After fix: [SMB_XP3R3V_TCXO_CIT_Fix.txt](https://github.com/facebookexternal/openbmc.celestica/files/15412741/SMB_XP3R3V_TCXO_CIT_Fix.txt)

```
root@bmc-oob:/run/tests2# python cit_runner.py -p fuji --run-test tests.fuji.test_sensor.SmbSensorTest
test_smb_sensor_keys (tests.fuji.test_sensor.SmbSensorTest.test_smb_sensor_keys) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.067s

OK
```

Reviewed By: mikechoifb

Differential Revision: D57710386

fbshipit-source-id: a3f5d9891fce29c2e96d491f7c1eead3cd793d0d