Common: cpld-fw-handler support XO3D CFG1 update and version reading
Summary:
- Support CFG1 update and CFG0/CFG1 version reading for LCMXO3D series CPLD.
- Add argument "-t,--target" to select target to update or read version.
When updating CPLD:
If the "target" argument is not set or is set to "CFG0", CFG0 is updated,
If the "target" argument is set to "CFG1", then CFG1 is updated.
When reading the CPLD version:
If the "target" argument is not set, the currently running version is read,
If the "target" argument is set to "CFG0", the CFG0 version is read,
If the "target" argument is set to "CFG1", the CFG1 version is read.

X-link: https://github.com/facebookexternal/openbmc.quanta/pull/4305

Test Plan:
- Build: PASS
- Read version: PASS
```
root@bmc:~# cpld-fw-handler version --help
Get Frimware Version
Usage: cpld-fw-handler version [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -i,--interface TEXT REQUIRED
                              interface
  -b,--bus UINT REQUIRED      i2c bus
  -a,--addr UINT REQUIRED     slave address
  -t,--target TEXT            used for LCMXO3D series CPLD, CFG0|CFG1
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44
CPLD version: 0x00000026
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t CFG0
CPLD CFG0 version: 0x00000026
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t CFG1
CPLD CFG1 version: 0x00000025
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t test
Error: unknown target.
Failed to get CPLD version
```
- Update: PASS
```
root@bmc:~# cpld-fw-handler update --help
CPLD FW TOOL VER 1.0
Usage: cpld-fw-handler update [OPTIONS]

Options:
  -h,--help                   Print this help message and exit
  -p,--path TEXT:FILE REQUIRED
                              image file path.
  -b,--bus UINT REQUIRED      i2c bus
  -a,--addr UINT REQUIRED     slave address
  -i,--interface TEXT REQUIRED
                              i2c
  -c,--chip TEXT REQUIRED     LCMXO3LF-4300|LCMXO3LF-6900|LCMXO3D-4300|LCMXO3D-9400
  -t,--target TEXT            used for LCMXO3D series CPLD, CFG0|CFG1
  -v,--verbose                debug mode
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t CFG0
CPLD CFG0 version: 0x00000026
root@bmc:~# cpld-fw-handler update -i i2c -b 8 -a 0x44 -c LCMXO3D-9400 -t CFG0 -p /tmp/V25.jed
Device ID = 21 2e 30 43 [OK] Device ID match with chip
NOTE DEVICE NAME:       LCMXO3D-9400HC-5CABGA400*
[OK] The image device name match with chip name
QF Size = 1f7e00
CF Size = 73744
UFM size = 1efd0
Checksum = 0x7f69
UserCode = 0x25
jedFileCheckSum = 537f69
JED File CheckSum = 0x7f69
Starts to update ...
Enable program mode.
Erase flash.
Reset config flash.
Write Program Page ...
Write Program Page Done.
Program user code.
Disable config interface.

Update completed! Please AC.
Execution time: 22 seconds
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t CFG0
CPLD CFG0 version: 0x00000025

root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t CFG1
CPLD CFG1 version: 0x00000025
root@bmc:~# cpld-fw-handler update -i i2c -b 8 -a 0x44 -c LCMXO3D-9400 -t CFG1 -p /tmp/V26.jed
Device ID = 21 2e 30 43 [OK] Device ID match with chip
NOTE DEVICE NAME:       LCMXO3D-9400HC-5CABGA400*
[OK] The image device name match with chip name
QF Size = 1f7e00
CF Size = 78640
UFM size = 1dcb0
Checksum = 0x2ff6
UserCode = 0x26
jedFileCheckSum = 5e2ff6
JED File CheckSum = 0x2ff6
Starts to update ...
Enable program mode.
Erase flash.
Reset config flash.
Write Program Page ...
Write Program Page Done.
Program user code.
Disable config interface.

Update completed! Please AC.
Execution time: 23 seconds
root@bmc:~# cpld-fw-handler version -i i2c -b 8 -a 0x44 -t CFG1
CPLD CFG1 version: 0x00000026
```

Reviewed By: jagpalgill

Differential Revision: D58178717

fbshipit-source-id: cd50c127cd3e8cd2b3569918e383dae05b133427