Adjust pattern matching in base log-util test
Summary:
Testing an angelslanding device against CIT suite, it was failing on log-util tests:

```
======================================================================
FAIL: test_log_format (tests.angelslanding.test_log_util.MbLogUtilTest.test_log_format)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/angelslanding/test_log_util.py", line 35, in test_log_format
    super().test_log_format()
  File "/run/tests2/common/base_log_util_test.py", line 92, in test_log_format
    self.assertIsNotNone(
AssertionError: unexpectedly None : no matching log found. output is 1    tray0_mb 2024-06-14 16:39:14    ipmid            SEL Entry: FRU: 1, Record: Facebook Unified SEL (0xFB), Gener
alInfo: MEMORY_ECC_ERR(0x21), DIMM Slot Location: Sled 01/Socket 03, Channel 01, Slot 00, DIMM B1, DIMM Failure Event: Memory correctable error (Patrol scrub)
1    tray0_mb 2024-06-28 10:14:53    ipmid            SEL Entry: FRU: 1, Record: Facebook Unified SEL (0xFB), GeneralInfo: MEMORY_ECC_ERR(0x21), DIMM Slot Location: Sled 01/Socket 03,
Channel 01, Slot 00, DIMM B1, DIMM Failure Event: Memory correctable error (Patrol scrub)

======================================================================
FAIL: test_log_format (tests.angelslanding.test_log_util.NicLogUtilTest.test_log_format)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/run/tests2/tests/angelslanding/test_log_util.py", line 35, in test_log_format
    super().test_log_format()
  File "/run/tests2/common/base_log_util_test.py", line 92, in test_log_format
    self.assertIsNotNone(
AssertionError: unexpectedly None : no matching log found. output is 3    tray0_nic0 2024-06-12 06:42:25    ncsid            FRU: 3 NIC AEN Supported: 0x7, AEN Enable Mask=0x7
3    tray0_nic0 2024-06-12 06:42:25    ncsid            FRU: 3 PLDM type supported = 0x35
3    tray0_nic0 2024-06-12 06:42:25    ncsid            FRU: 3 PLDM type 0 version = 1.0.0.0
3    tray0_nic0 2024-06-12 06:42:25    ncsid            FRU: 3 PLDM type 2 version = 1.1.0.0
3    tray0_nic0 2024-06-12 06:42:26    ncsid            FRU: 3 PLDM type 4 version = 1.0.0.0
3    tray0_nic0 2024-06-12 06:42:26    ncsid            FRU: 3 PLDM type 5 version = 1.0.0.0
3    tray0_nic0 2024-06-12 06:42:26    ncsid            FRU: 3 PLDM sensor monitoring enabled
3    tray0_nic0 2024-07-03 04:52:38    ncsid            FRU: 3 NIC AEN Supported: 0x7, AEN Enable Mask=0x7
3    tray0_nic0 2024-07-03 04:52:38    ncsid            FRU: 3 PLDM type supported = 0x35
3    tray0_nic0 2024-07-03 04:52:38    ncsid            FRU: 3 PLDM type 0 version = 1.0.0.0
3    tray0_nic0 2024-07-03 04:52:38    ncsid            FRU: 3 PLDM type 2 version = 1.1.0.0
3    tray0_nic0 2024-07-03 04:52:39    ncsid            FRU: 3 PLDM type 4 version = 1.0.0.0
3    tray0_nic0 2024-07-03 04:52:39    ncsid            FRU: 3 PLDM type 5 version = 1.0.0.0
3    tray0_nic0 2024-07-03 04:52:39    ncsid            FRU: 3 PLDM sensor monitoring enabled

----------------------------------------------------------------------
```
However, all looks fine in terms of the content. Seems the reason for failure is differences in whitespace between items. This shouldn't cause a failure, so let's make the whitespace expectations a little less specific

Test Plan:
```
$ python3 tests2/openbmc_tester.py --hostname rtptest1659-oob.ftw6 --password "***********" --platform angelslanding
test_boot_order_disable (tests.angelslanding.test_bios_util.BiosUtilTest.test_boot_order_disable)
Test CLI: bios-util server --boot_order disable --clear_CMOS ... ok
test_boot_order_enable (tests.angelslanding.test_bios_util.BiosUtilTest.test_boot_order_enable)
Test CLI: bios-util server --boot_order enable --clear_CMOS ... ok
test_boot_order_get (tests.angelslanding.test_bios_util.BiosUtilTest.test_boot_order_get)
Test CLI: bios-util server --boot_order get --boot_order ... ok
test_boot_order_set_bootmode (tests.angelslanding.test_bios_util.BiosUtilTest.test_boot_order_set_bootmode)
Test CLI: bios-util server --boot_order set --boot_mode ... ok
test_postcode_get (tests.angelslanding.test_bios_util.BiosUtilTest.test_postcode_get) ... ok
test_busybox_usage_strings (tests.angelslanding.test_busybox_syntax.BusyBoxSyntaxTest.test_busybox_usage_strings) ... ok
test_cpu_utilization (tests.angelslanding.test_cpu_utilization.CpuUtilizationTest.test_cpu_utilization)
This test is ran a specific number of time ... ok
test_eth0_v4_interface (tests.angelslanding.test_interface.InterfaceTest.test_eth0_v4_interface)
Tests eth0 v4 interface ... skipped 'Test not supported in environment'
test_eth0_v6_interface (tests.angelslanding.test_interface.InterfaceTest.test_eth0_v6_interface)
Tests eth0 v6 interface ... ok
test_kernel_path_exists (tests.angelslanding.test_kernel_abi.KernelABITest.test_kernel_path_exists) ... ok
test_log_clear (tests.angelslanding.test_log_util.AllLogUtilTest.test_log_clear) ... skipped 'not available'
test_log_format (tests.angelslanding.test_log_util.AllLogUtilTest.test_log_format) ... ok
test_log_format_json (tests.angelslanding.test_log_util.AllLogUtilTest.test_log_format_json)
test log-util [FRU] --print --json and verify output ... ok
test_log_clear (tests.angelslanding.test_log_util.MbLogUtilTest.test_log_clear) ... skipped 'not available'
test_log_format (tests.angelslanding.test_log_util.MbLogUtilTest.test_log_format) ... ok
test_log_format_json (tests.angelslanding.test_log_util.MbLogUtilTest.test_log_format_json)
test log-util [FRU] --print --json and verify output ... ok
test_log_clear (tests.angelslanding.test_log_util.NicLogUtilTest.test_log_clear) ... skipped 'not available'
test_log_format (tests.angelslanding.test_log_util.NicLogUtilTest.test_log_format) ... ok
test_log_format_json (tests.angelslanding.test_log_util.NicLogUtilTest.test_log_format_json)
test log-util [FRU] --print --json and verify output ... ok
test_log_clear (tests.angelslanding.test_log_util.SysLogUtilTest.test_log_clear)
test to clear SEL ... ok
test_log_format (tests.angelslanding.test_log_util.SysLogUtilTest.test_log_format)
test log-util [FRU] --print and verify output ... ok
test_log_format_json (tests.angelslanding.test_log_util.SysLogUtilTest.test_log_format_json)
test log-util [FRU] --print --json and verify output ... ok
test_installed_processes (tests.angelslanding.test_process_running.ProcessRunningTest.test_installed_processes) ... ok
test_img_signing_key (tests.angelslanding.test_vboot.VBootCheckTest.test_img_signing_key)
Test all measures ... ok

----------------------------------------------------------------------
Ran 24 tests in 327.158s

OK (skipped=4)
```

Reviewed By: lsiudut

Differential Revision: D59323686

fbshipit-source-id: 5a1e2c7e5181d6060035708beb7632753a173267