cit: montblanc: test_interface for ping x86 usb0 interface
Summary:
# Description
add cit for ping x86 test in montblanc platform

# Motivation
to verify usb0 interface able use interface with COMe x86

X-link: https://github.com/facebookexternal/openbmc.celestica/pull/1747

Test Plan:
test on Tahan platform
```
root@bmc-oob:/usr/local/bin/tests2# ifconfig usb0 up
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p montblanc -r tests.montblanc.test_interface
test_eth0_v4_interface (tests.montblanc.test_interface.InterfaceTest.test_eth0_v4_interface)
Tests eth0 v4 interface ... ok
test_eth0_v6_interface (tests.montblanc.test_interface.InterfaceTest.test_eth0_v6_interface)
Tests eth0 v6 interface ... ok
test_usb0_v6_interface (tests.montblanc.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests usb0 v6 interface ... ok
test_usb0_v6_x86_interface (tests.montblanc.test_interface.InterfaceTest.test_usb0_v6_x86_interface)
Tests usb0 v6 interface ping to x86 side ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.092s

OK
```
try down usb0 interface and test again, should show failed
```
root@bmc-oob:/usr/local/bin/tests2# ifconfig usb0 down
root@bmc-oob:/usr/local/bin/tests2# python cit_runner.py -p montblanc -r tests.montblanc.test_interface
test_eth0_v4_interface (tests.montblanc.test_interface.InterfaceTest.test_eth0_v4_interface)
Tests eth0 v4 interface ... ok
test_eth0_v6_interface (tests.montblanc.test_interface.InterfaceTest.test_eth0_v6_interface)
Tests eth0 v6 interface ... ok
test_usb0_v6_interface (tests.montblanc.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests usb0 v6 interface ... ERROR
test_usb0_v6_x86_interface (tests.montblanc.test_interface.InterfaceTest.test_usb0_v6_x86_interface)
Tests usb0 v6 interface ping to x86 side ... ERROR

======================================================================
ERROR: test_usb0_v6_interface (tests.montblanc.test_interface.InterfaceTest.test_usb0_v6_interface)
Tests usb0 v6 interface
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/montblanc/test_interface.py", line 48, in test_usb0_v6_interface
    self.assertEqual(self.ping_v6(), 0, "Ping test for usb0 v6 failed")
                     ^^^^^^^^^^^^^^
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 122, in ping_v6
    ip = self.get_ipv6_address()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 98, in get_ipv6_address
    ipv6 = self.get_ip_addr_output_inet6()[1].split("/")[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 86, in get_ip_addr_output_inet6
    raise Exception(
Exception: Device usb0 does not have an IPv6 address [FAILED]
command output:4: usb0: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 64
    link/ether 02:00:00:00:00:01 brd ff:ff:ff:ff:ff:ff

======================================================================
ERROR: test_usb0_v6_x86_interface (tests.montblanc.test_interface.InterfaceTest.test_usb0_v6_x86_interface)
Tests usb0 v6 interface ping to x86 side
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/tests2/tests/montblanc/test_interface.py", line 57, in test_usb0_v6_x86_interface
    self.assertEqual(self.run_ping(cmd), 0, "Ping test for x86 failed")
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/tests2/common/base_interface_test.py", line 111, in run_ping
    raise Exception(err)
Exception: b'ping6: sendto: Network is unreachable\n'

----------------------------------------------------------------------
Ran 4 tests in 0.087s

FAILED (errors=2)
root@bmc-oob:/usr/local/bin/tests2#
```

Reviewed By: mikechoifb

Differential Revision: D55469596

fbshipit-source-id: fb2a7816964a7ddd0eb118ff6652f85ac8c3e00b