common: fix REST API and RED FISH EVENTS crash (#3024)
Summary:
# Description:
 - REST API and RED FISH EVENTS services meet error and crash which causing servcies keep restarting
```
from .helpers import ( File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 229, in <module> attr.s(auto_attribs=True, frozen=True, slots=True)
^^^^^^
AttributeError: module 'attr' has no attribute 's'

 run: restapi: (pid 10137) 1s
 root@bmc-oob:/etc/init.d# sv staus restapi
 run: restapi: (pid 10137) 2s
 root@bmc-oob:/etc/init.d# sv staus restapi
 run: restapi: (pid 10171) 0s
 root@bmc-oob:/etc/init.d#
 run: redfishevents: (pid 10482) 2s
 root@bmc-oob:/etc/init.d# sv status redfishevents
 down: redfishevents: 0s, normally up, want up
 root@bmc-oob:/etc/init.d# sv status redfishevents
 run: redfishevents: (pid 10489) 0s
 root@bmc-oob:/etc/init.d# sv status redfishevents
 run: redfishevents: (pid 10489) 1s
 ```
 - The crash of REST API and RED FISH EVENTS causing these services keep restarting and CPU high loading.

 # Motivation:
 - To fix REST API and RED FISH EVENTS crashing

Pull Request resolved: https://github.com/facebookexternal/openbmc.wiwynn/pull/3024

Test Plan:
- Built passed on GTA and RED FISH/REST API can work normally instead of crashing - pass

 # Log:
 REST API:
 - Before Change
 ```root@bmc-oob:~# python3 /usr/local/bin/rest.py Traceback (most recent call last):
  File "/usr/local/bin/rest.py", line 31, in <module>
    import rest_debug
  File "/usr/local/fbpackages/rest-api/rest_debug.py", line 8, in <module>
    from aiohttp.log import server_logger
  File "/usr/lib/python3.12/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 38, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3.12/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3.12/site-packages/aiohttp/http_parser.py", line 30, in <module>
    from .helpers import (
  File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 229, in <module>
    attr.s(auto_attribs=True, frozen=True, slots=True)
     ^^^^^^
AttributeError: module 'attr' has no attribute 's' root@bmc-oob:~#
 ```
 - After Change
 ```root@bmc-oob:~# python3 /usr/local/bin/rest.py Creating new webapp
/usr/local/bin/rest.py:74: DeprecationWarning: Application.make_handler(...) is deprecated, use AppRunner API instead
  handler = app.make_handler(
/usr/local/bin/rest.py:122: DeprecationWarning: Changing state of started or joined application is deprecated
  app["acl_provider"] = load_acl_provider(config)
 ```

 RED FISH EVENTS:
 - Before Change
 ```root@bmc-oob:~#  /usr/bin/python3 /usr/bin/redfish-events.py Traceback (most recent call last):
  File "/usr/bin/redfish-events.py", line 14, in <module>
    from aiohttp import web
  File "/usr/lib/python3.12/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import (
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 38, in <module>
    from . import hdrs, http, payload
  File "/usr/lib/python3.12/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/usr/lib/python3.12/site-packages/aiohttp/http_parser.py", line 30, in <module>
    from .helpers import (
  File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 229, in <module>
    attr.s(auto_attribs=True, frozen=True, slots=True)
     ^^^^^^
AttributeError: module 'attr' has no attribute 's' root@bmc-oob:~#
 ```
 - After Change
 ``` root@bmc-oob:~# /usr/bin/python3 /usr/bin/redfish-events.py /usr/bin/redfish-events.py:17: DeprecationWarning: Inheritance class RedfishEventHandler from web.Application is discouraged
  class RedfishEventHandler(web.Application):
 ```

Reviewed By: williamspatrick

Differential Revision: D55580052

fbshipit-source-id: 9c293ac76cbc60cd6f31ecfc9cd3309e2455dfa3